### ISSUE TITLE
pred predlozkou nemusi byt vzdy mezera

### ISSUE THREAD

**Issue by m-blaha** [felixprojekt/nbsp2preposition#1]
Například předložky na začátku závorky nejsou ošetřeny (s použitím regulárních výrazů by to šlo lépe.)

**Comment by felixprojekt** [comment]
Díky, to je pravda. Nastuduji regulérní výrazy.

**Comment by felixprojekt** [comment]
Nakonec jsem se rozhodl nelámat si s tím hlavu a jen jsem přidal další podmínky nahrazení.
